<?php
$HOST = 'localhost';
$BASEDEDATOS = 'mutual';
$USUARIO = 'root';
$PASS = '';
$TABLETMP='tmp';
$TABLEAFILIADOS='tafiliados';
$IDENUNICO="COD_AFILIADO";
$ESTADOAFILIACION="COD_ESTADO_AFILIACION2";
$FECHANACIMIENTO="FECHA_NACIMIENTO";
$EDAD="EDAD";
$NI="NUMERO_IDENTIFICACION";
?>